### PR TITLE
Added a new hdfsdirectory provider and modified default.rb to install we...

### PR DESCRIPTION
**Pull request by amithkanand**
...bhdfs gem

### CODE REVIEW

**Comment by amithkanand** [comment]
Added new provider for creating directory on HDFS.

**Comment by cbaenziger** [comment]
This is looking very good and will make dealing with HDFS much nicer.
- A nit, please use a smaller indent (perhaps 2 space)?
- Could you ensure the gem is installed?

Gem install is probably two-step:
1. Download the gem using [build_bins.sh](https://github.com/bloomberg/chef-bcpc/blob/hadoop_hortonworks/build_bins.sh#L56-L60)
2. Follow the [zookeeper](https://github.com/bloomberg/chef-bcpc/blob/hadoop_hortonworks/cookbooks/bcpc-hadoop/recipes/default.rb#L24-L44) approach of installing

Oh; it looks like you have step-2 of the gem install in place too.

**Comment by amithkanand** [comment]
Corrected indentation and added webhdfs gem to build_bins.sh

**Comment by amithkanand** [comment]
Corrected Indentation

**Pull request merged**
